### ISSUE TITLE
Potential hardcoded secret

### ISSUE THREAD

**Issue by SlimTrabelsi** [tuhh-softsec/DockerCleaner#1]
Hi,

It seems that you published several hardcoded secrets like the following:

https://github.com/tuhh-softsec/DockerCleaner/blob/3281dbc9c77367845abd3402bed8477b89ae8e8e/dataset/fixed_binnacle_dockerfiles/a576e80bba15f87650f450689047693d97dbcbd2.dockerfile#L47
https://github.com/tuhh-softsec/DockerCleaner/blob/3281dbc9c77367845abd3402bed8477b89ae8e8e/dataset/fixed_binnacle_dockerfiles/58bfc5ecad011505e5c03978901cefb20f61a898.dockerfile#L62
https://github.com/tuhh-softsec/DockerCleaner/blob/3281dbc9c77367845abd3402bed8477b89ae8e8e/dataset/smelly_dockerfiles/arangodb__3.9__8__injected.dockerfile#L41
https://github.com/tuhh-softsec/DockerCleaner/blob/3281dbc9c77367845abd3402bed8477b89ae8e8e/dataset/smelly_dockerfiles/eclipse-mosquitto__1.5.11__9__injected.dockerfile#L60

There are much more secrets detected.
Please let me know if it helps and if you need the entire list of secrets
thank you

**Comment by bqcuong** [comment]
Hi,

Thanks for your nice contribution anyway ;)
