### ISSUE TITLE
Links to Pull Requests Don't Work

### ISSUE THREAD

**Issue by JLLeitschuh** [tuhh-softsec/DockerCleaner#2]
Hello!

It seems that the links to these pull requests seem to all be dead links:

https://github.com/tuhh-softsec/DockerCleaner/blob/8c508a958dff15b1c20bbd1b8a28d15680d19c27/README.md?plain=1#L44-L55

**Comment by bqcuong** [comment]
Hi @JLLeitschuh,

Thanks for your interest in our work.

These anonymous links were used during the paper's peer review.
Now updated with the original pull request links https://github.com/tuhh-softsec/DockerCleaner/commit/5cef7a9.
Btw, did you take a look at our paper? I am happy to answer your questions about DockerCleaner.

Sincerely,
Cuong
